# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - webenv-shufl-qa(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
      
    - run: 'echo "$PROFILE" > profile.txt'
      shell: bash
      env:
        PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_72E761F3538C4F2EAA77DB9DCB32AFF4 }}


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: webenv-shufl-qa
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_72E761F3538C4F2EAA77DB9DCB32AFF4 }}
        package: ${{env.DOTNET_ROOT}}/myapp

