name: PR - Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup nuget sources
      run: dotnet nuget add source https://nuget.pkg.github.com/Web-Env/index.json -n GPR -u AdamBOD -p ${{ secrets.GPR_TOKEN }} --store-password-in-clear-text
    - name: Clean
      run: dotnet clean ./Shufl.API.sln -- configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore --disable-parallel
    - name: Configure App Settings
      uses: microsoft/variable-substitution@v1 
      with:
        files: './Shufl.API/appsettings.json'
      env:
        SmtpSettings.EmailSmtpPassword: ${{ secrets.SMTP_PASSWORD }}
        EmailSettings.PrimaryRedirectUrl: ${{ secrets.PRIMARY_REDIRECT_URL }}
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
